/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TmpClass */

#ifndef _Included_TmpClass
#define _Included_TmpClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TmpClass
 * Method:    intSumMethod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TmpClass_intSumMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TmpClass
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_TmpClass_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     TmpClass
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TmpClass_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TmpClass
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_TmpClass_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
